import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Alert, Box, Button, CircularProgress, FormControlLabel, Paper, Stack, Switch, ToggleButton, ToggleButtonGroup, Typography, } from '@mui/material';
import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import CopyButton from '../components/CopyButton';
import LottoBall from '../components/LottoBall';
import { v1Api } from '../api/v1Api';
const LOOKBACK_OPTIONS = [5, 10, 20];
export default function GeneratorPage() {
    const [lookback, setLookback] = useState(5);
    const [excludeConsecutive, setExcludeConsecutive] = useState(false);
    const generate = useMutation({
        mutationFn: () => v1Api.generateWeighted({ nSets: 6, lookback, excludeConsecutive }),
    });
    return (_jsxs(Box, { children: [_jsx(Typography, { variant: "h5", fontWeight: 800, gutterBottom: true, children: "\uBC88\uD638 \uC0DD\uC131\uAE30" }), _jsx(Typography, { variant: "body2", color: "text.secondary", sx: { mb: 2 }, children: "\uCD5C\uADFC \uBBF8\uCD9C\uD604 \uBC88\uD638\uC5D0 +15% \uAC00\uC911\uCE58\uB97C \uBD80\uC5EC\uD55C \uD1B5\uACC4 \uAE30\uBC18 \uCD94\uCC9C" }), _jsxs(Paper, { sx: { p: 2, mb: 2 }, children: [_jsx(Typography, { variant: "subtitle2", gutterBottom: true, children: "\uBBF8\uCD9C\uD604 \uAE30\uC900 (\uCD5C\uADFC \uD68C\uCC28)" }), _jsx(ToggleButtonGroup, { exclusive: true, value: lookback, onChange: (_, v) => v && setLookback(v), size: "small", sx: { mb: 2 }, children: LOOKBACK_OPTIONS.map((opt) => (_jsxs(ToggleButton, { value: opt, children: ["\uCD5C\uADFC ", opt, "\uD68C"] }, opt))) }), _jsx(FormControlLabel, { control: _jsx(Switch, { checked: excludeConsecutive, onChange: (e) => setExcludeConsecutive(e.target.checked) }), label: "\uC5F0\uC18D \uBC88\uD638 \uC81C\uC678" })] }), _jsx(Button, { variant: "contained", color: "warning", size: "large", onClick: () => generate.mutate(), disabled: generate.isPending, sx: { mb: 2, fontWeight: 800 }, children: generate.isPending ? _jsx(CircularProgress, { size: 24, color: "inherit" }) : '번호 생성' }), generate.isError && (_jsx(Alert, { severity: "error", sx: { mb: 2 }, children: generate.error instanceof Error ? generate.error.message : '생성 실패' })), generate.data?.warning && (_jsx(Alert, { severity: "warning", sx: { mb: 2 }, children: generate.data.warning })), generate.data && (_jsxs(Box, { children: [generate.data.unseen_numbers.length > 0 && (_jsxs(Typography, { variant: "body2", color: "success.main", sx: { mb: 1 }, children: ["\uAC00\uC911\uCE58 \uBD80\uC5EC \uBC88\uD638: ", generate.data.unseen_numbers.join(', ')] })), generate.data.combinations.map((combo, idx) => (_jsxs(Paper, { sx: { p: 2, mb: 1, display: 'flex', alignItems: 'center', gap: 1 }, children: [_jsx(Typography, { sx: { width: 24, fontWeight: 800, color: 'text.secondary' }, children: String.fromCharCode(65 + idx) }), _jsx(Stack, { direction: "row", spacing: 0.75, flexWrap: "wrap", useFlexGap: true, sx: { flex: 1 }, children: combo.numbers.map((n) => (_jsx(LottoBall, { number: n, size: 38 }, n))) }), _jsxs(Box, { sx: { textAlign: 'right' }, children: [_jsxs(Typography, { variant: "caption", color: "text.secondary", display: "block", children: ["\uD569 ", combo.sum_total] }), _jsx(CopyButton, { numbers: combo.numbers })] })] }, idx)))] }))] }));
}
