import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Alert, Box, Button, CircularProgress, Paper, Stack, ToggleButton, ToggleButtonGroup, Typography, } from '@mui/material';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import CopyButton from '../components/CopyButton';
import LottoBall from '../components/LottoBall';
import { v1Api } from '../api/v1Api';
export default function RoundRecommendPage() {
    const [machine, setMachine] = useState('auto');
    const meta = useQuery({ queryKey: ['v1-meta'], queryFn: v1Api.getMeta });
    const recommend = useQuery({
        queryKey: ['v1-recommend', machine],
        queryFn: () => v1Api.getRoundRecommend(machine === 'auto' ? undefined : machine),
    });
    const data = recommend.data;
    return (_jsxs(Box, { children: [_jsx(Typography, { variant: "h5", fontWeight: 800, gutterBottom: true, children: "\uD68C\uCC28 \uCD94\uCC9C" }), _jsxs(Typography, { variant: "body2", color: "text.secondary", sx: { mb: 1 }, children: [meta.data?.current_round ?? '—', "\uD68C \uCD94\uCCA8 \uAE30\uC900 \u00B7 \uD638\uAE30 \uD328\uD134 5\uAC8C\uC784", meta.data ? ` (데이터 ${meta.data.row_count}건)` : ''] }), _jsx(Alert, { severity: "info", sx: { mb: 2 }, children: "\uD638\uAE30\uB294 \uCD94\uCCA8\uC77C \uAE30\uBC18 \uCD94\uC815\uAC12\uC785\uB2C8\uB2E4. \uACF5\uC2DD \uBC1C\uD45C\uC640 \uB2E4\uB97C \uC218 \uC788\uC73C\uBA70 \uD1B5\uACC4 \uCC38\uACE0\uC6A9\uC785\uB2C8\uB2E4." }), data && (_jsxs(Paper, { sx: { p: 2, mb: 2, bgcolor: '#69C8F2', color: '#10202A' }, children: [_jsx(Typography, { variant: "caption", fontWeight: 600, children: "\uCD94\uCC9C \uB300\uC0C1" }), _jsxs(Typography, { variant: "h3", fontWeight: 800, children: [data.next_round, "\uD68C"] }), _jsxs(Typography, { variant: "body2", children: ["\uC608\uC0C1 \uCD94\uCCA8\uC77C ", data.next_draw_date, " \u00B7 ", data.machine_id, "\uD638\uAE30", data.machine_id !== data.auto_machine_id
                                ? ` (자동예측 ${data.auto_machine_id}호기)`
                                : ''] })] })), _jsxs(Paper, { sx: { p: 2, mb: 2 }, children: [_jsx(Typography, { variant: "subtitle2", gutterBottom: true, children: "\uBD84\uC11D \uD638\uAE30" }), _jsx(ToggleButtonGroup, { exclusive: true, value: machine, onChange: (_, v) => v && setMachine(v), size: "small", children: ['auto', 1, 2, 3].map((opt) => (_jsx(ToggleButton, { value: opt, children: opt === 'auto' ? '자동' : `${opt}호기` }, String(opt)))) })] }), _jsx(Button, { variant: "contained", color: "warning", onClick: () => recommend.refetch(), disabled: recommend.isFetching, sx: { mb: 2, fontWeight: 800 }, children: recommend.isFetching ? _jsx(CircularProgress, { size: 24, color: "inherit" }) : '회차 추천 받기' }), recommend.isError && (_jsx(Alert, { severity: "error", sx: { mb: 2 }, children: recommend.error instanceof Error ? recommend.error.message : '추천 실패' })), data?.warning && (_jsx(Alert, { severity: "warning", sx: { mb: 2 }, children: data.warning })), data && data.stats.draw_count > 0 && (_jsxs(Paper, { sx: { p: 2, mb: 2 }, children: [_jsx(Typography, { variant: "subtitle1", fontWeight: 700, children: "\uD638\uAE30 \uD1B5\uACC4 \uC694\uC57D" }), _jsxs(Typography, { variant: "body2", color: "text.secondary", children: ["\uBD84\uC11D ", data.stats.draw_count, "\uD68C \u00B7 \uD3C9\uADE0\uD569 ", data.stats.avg_sum, " \u00B7 \uD640", ' ', data.stats.avg_odd] }), _jsx(Typography, { variant: "caption", color: "warning.main", sx: { mt: 1, display: 'block' }, children: "\uCD5C\uB2E4 \uCD9C\uD604 TOP 5" }), _jsx(Typography, { variant: "body2", children: data.stats.hot_top5.map((h) => `${h.number}(${h.count})`).join('  ') }), _jsx(Typography, { variant: "caption", color: "warning.main", sx: { mt: 1, display: 'block' }, children: "\uBBF8\uCD9C\uD604 TOP 5" }), _jsx(Typography, { variant: "body2", children: data.stats.cold_top5.map((c) => `${c.number}(${c.gap_rounds})`).join('  ') })] })), data && data.combinations.length > 0 && (_jsxs(Box, { children: [_jsx(Typography, { variant: "subtitle1", fontWeight: 700, children: "\uCD94\uCC9C 5\uAC8C\uC784" }), _jsxs(Typography, { variant: "caption", color: "text.secondary", sx: { mb: 1, display: 'block' }, children: [data.compose_rule, " \u00B7 ", data.filter_rule] }), data.combinations.map((combo, idx) => (_jsxs(Paper, { sx: { p: 2, mb: 1, display: 'flex', alignItems: 'center', gap: 1 }, children: [_jsx(Typography, { sx: { width: 22, fontWeight: 800, color: 'text.secondary' }, children: idx + 1 }), _jsx(Stack, { direction: "row", spacing: 0.75, flexWrap: "wrap", useFlexGap: true, sx: { flex: 1 }, children: combo.numbers.map((n) => (_jsx(LottoBall, { number: n, size: 36 }, n))) }), _jsxs(Box, { sx: { textAlign: 'right' }, children: [_jsxs(Typography, { variant: "caption", color: "text.secondary", display: "block", children: ["\uD569", combo.sum_total, " \u00B7 \uD640", combo.odd_count] }), _jsx(CopyButton, { numbers: combo.numbers })] })] }, idx)))] }))] }));
}
